name = "ConcaveHull"
uuid = "7d11a335-8259-52c9-8750-e30c45c66484"
author = ["Luke Stagner <stagnerl@fusion.gat.com>"]
version = "1.0.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NearestNeighbors = "b8a86587-4115-5ab1-83bc-aa920d37bbce"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"

[compat]
NearestNeighbors = "^0.4.3"
RecipesBase = "^0.7"
julia = "^1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
